services:
  flask_app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5000  # Points to local MLflow server
    networks:
      - ml_network
    depends_on:
      - elasticsearch

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi  # Create this file if you have FastAPI
    ports:
      - "8000:8000"
    environment:
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5000  # Points to local MLflow server
    networks:
      - ml_network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - ml_network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.9
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - ml_network

volumes:
  esdata:

networks:
  ml_network:
    driver: bridge